### ISSUE TITLE
English documentation + demo

### ISSUE THREAD

**Issue by tristanbes** [FairyEver/d2admin-vue-element#1]
It would be awesome for the rest of the world :D

**Comment by FairyEver** [comment]
I am very sorry about this. Because I have limited time and energy to do this project, I need to spend more time on the maintenance code at this stage. I will translate the English version in the future.

**Comment by WoopDogg** [comment]
Nice

**Comment by FairyEver** [comment]
In the first major version at present, some designs make it inconvenient for us to internationalize, and we will pay attention to the problems of English demonstration and documents when we refactor the code in the future version 2.0

**Comment by ttodua** [comment]
The DEMO (Preview) is in chinese. You are just loosing much. If there was ENGLISH version, people would be interested. Even Google Translate -embeded button might be something more than nothing.
