### ISSUE TITLE
导入xlsx和csv这个功能很方便，可以单独拿出来用么

### ISSUE THREAD

**Issue by yh4922** [FairyEver/d2admin-vue-element#2]
导入xlsx和csv这个功能很方便，可以单独拿出来用么

**Comment by FairyEver** [comment]
分别是这两个文件
[export/index.js](https://github.com/FairyEver/d2admin-vue-element/blob/master/src/plugin/export/index.js) 和 [import/index.js](https://github.com/FairyEver/d2admin-vue-element/blob/master/src/plugin/import/index.js)。已经写成了vue插件的形式，你可以拿出来随意去你的项目里使用
