### ISSUE TITLE
您好，非常喜欢您的作品，想将这个项目和electron结合一起用，不知道怎么做？求指教

### ISSUE THREAD

**Issue by lhz1208** [FairyEver/d2admin-vue-element#6]
您好，非常喜欢您的作品，想将这个项目和electron结合一起用，不知道怎么做？求指教，merge代码总是在报错。

**Comment by FairyEver** [comment]
您好，我建议您使用 [electron-vue](https://electron.org.cn/vue/index.html) 和本项目配合使用，理论上说应该无需大改动，先初始化好electron-vue项目，再将d2admin放进去
目前我暂时能想到的需要额外修改的地方：
* 请注意electron的env设置方式 下面的地方如果还保留的话请自行修改
https://github.com/FairyEver/d2admin-vue-element/blob/971169256f65fb4c0ed2eb0e2b1d08933a4203d0/src/pages/demo/plugins/build/index.vue#L6
https://github.com/FairyEver/d2admin-vue-element/blob/971169256f65fb4c0ed2eb0e2b1d08933a4203d0/src/main.js#L51
* 请注意需要安装scss
* 请注意需要安装svg-sprite-loader (dev)

**Comment by lhz1208** [comment]
谢谢您 我试试哈
